import{S as P,i as c,a as $}from"./assets/vendor-DuFnt2m8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const A=document.querySelector("#search-form"),u=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".loader-text"),f=document.querySelector(".load-more-btn"),H="32475203-0397f154fda8b2c2a6bae1f0a",M="https://pixabay.com/api/",y=40;let n=1,d="",l=0;const g=new P(".gallery a",{captionsData:"alt",captionDelay:250});A.addEventListener("submit",R);f.addEventListener("click",x);async function R(e){e.preventDefault();const r=e.currentTarget,i=r.elements.searchQuery.value.trim();if(!i){c.error({title:"Hata",message:"Arama kutusu boş olamaz!",position:"topRight"});return}d=i,n=1,u.innerHTML="",m(),S();try{const s=await b(d,n);l=s.totalHits,l===0?c.info({title:"Bilgi",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(L(s.hits),g.refresh(),w())}catch(s){B(s)}finally{v(),r.reset()}}async function x(){n+=1,m(),S();try{const e=await b(d,n);L(e.hits),g.refresh(),T(),w()}catch(e){B(e)}finally{v()}}async function b(e,r){const i={key:H,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:y};return(await $.get(M,{params:i})).data}function L(e){const r=e.map(({webformatURL:i,largeImageURL:s,tags:t,likes:o,views:a,comments:E,downloads:q})=>`<li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${i}" alt="${t}" loading="lazy"/>
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${o}</p>
            <p class="info-item"><b>Views</b> ${a}</p>
            <p class="info-item"><b>Comments</b> ${E}</p>
            <p class="info-item"><b>Downloads</b> ${q}</p>
          </div>
        </li>`).join("");u.insertAdjacentHTML("beforeend",r)}function S(){h.classList.remove("hidden"),p.classList.remove("hidden")}function v(){h.classList.add("hidden"),p.classList.add("hidden")}function O(){f.classList.remove("hidden")}function m(){f.classList.add("hidden")}function w(){n*y>=l?(m(),l>0&&c.info({title:"Bilgi",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):O()}function T(){const e=u.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}function B(e){c.error({title:"Hata",message:`Bir hata oluştu: ${e.message}`,position:"topRight"}),console.error("Fetch Error:",e)}
//# sourceMappingURL=index.js.map
